### ISSUE TITLE
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！ 联系人不在列表中，请查证后添加!!

### ISSUE THREAD

**Issue by moxiaoyuancl** [gzldc/12306#15]

**Comment by moxiaoyuancl** [comment]
我有乘车人 12306上也有

**Comment by ChenYiGeEr** [comment]
应该是你tk过期了，请求获取乘车人的接口报错了，重新获取下tk就好了。

**Comment by raydied4** [comment]
求助这种错误
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "C:\Users\Administrator\Downloads\Compressed\12306-master\init\select_ticket_info.py", line 115, in main
    l.reqLiftTicketInit()
  File "C:\Users\Administrator\Downloads\Compressed\12306-master\inter\LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by ChenYiGeEr** [comment]
@raydied4 应该是请求登录接口(https://kyfw.12306.cn/otn/leftTicket/init)获取到了空响应
