### ISSUE TITLE
select_ticket_info.select().main()，求助

### ISSUE THREAD

**Issue by raydied4** [gzldc/12306#18]
报错信息，求助
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "C:\Users\Administrator\Downloads\Compressed\12306-master\init\select_ticket_info.py", line 115, in main
    l.reqLiftTicketInit()
  File "C:\Users\Administrator\Downloads\Compressed\12306-master\inter\LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by stockbsd** [comment]
re.search('var CLeftTicketUrl = '(.*)'', result, re.M|re.I)
把字符串 外层的单引号改为 双引号，去掉\。
