### ISSUE TITLE
empty range for randrange() (4,4, 0)

### ISSUE THREAD

**Issue by weil-f** [gzldc/12306#29]
运行一段时间后，报错
empty range for randrange() (4,4, 0)，哪位老哥解决了

**Comment by weil-f** [comment]
还有如下错误
车次：G405 出发站：北京西 到达站：邯郸东 历时：02:07 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：G1591 出发站：北京西 到达站：邯郸东 历时：02:17 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：K589 出发站：北京西 到达站：邯郸东 历时：05:10 商务/特等座：-- 一等座：-- 二等座：-- 动卧：-- 硬卧：无 软座：无 硬座：无 无座：-- 预订
车次：G557 出发站：北京西 到达站：邯郸东 历时：02:09 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：K117 出发站：北京西 到达站：邯郸东 历时：05:54 商务/特等座：-- 一等座：-- 二等座：-- 动卧：-- 硬卧：无 软座：无 硬座：无 无座：-- 预订
车次：G401 出发站：北京西 到达站：邯郸东 历时：02:05 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：G1577 出发站：北京西 到达站：邯郸东 历时：02:05 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：G491 出发站：北京西 到达站：邯郸东 历时：02:19 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
车次：T145 出发站：北京西 到达站：邯郸东 历时：04:35 商务/特等座：-- 一等座：-- 二等座：-- 动卧：-- 硬卧：无 软座：无 硬座：无 无座：无 预订
车次：K267 出发站：北京西 到达站：邯郸东 历时：05:29 商务/特等座：-- 一等座：-- 二等座：-- 动卧：-- 硬卧：无 软座：无 硬座：无 无座：-- 预订
车次：G1575 出发站：北京西 到达站：邯郸东 历时：02:24 商务/特等座：无 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/project/12306-master/init/select_ticket_info.py", line 210, in main
    c.sendChechFace()
  File "/project/12306-master/inter/ChechFace.py", line 68, in sendChechFace
    g.sendSuccessRate()
  File "/project/12306-master/inter/GetSuccessRate.py", line 32, in sendSuccessRate
    successRateRsp = self.session.httpClint.send(urls.get("getSuccessRate"), self.data_apr())
  File "/project/12306-master/myUrllib/httpUtils.py", line 196, in send
    url_host = self.cdnList.pop(random.randint(0, 4))
IndexError: pop index out of range

**Comment by XiaoTianJianJun** [comment]
empty range for random range我也遇到了
